version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  app:
    depends_on:
      - mongo
    image: tahabozdemir/linksaver:0.0.1
    environment:
      - LINKSAVER_AUTH_DB_NAME=admin
      - LINKSAVER_DB_HOST=mongo
      - LINKSAVER_DB_PORT=27017
      - LINKSAVER_DB_NAME=mongodb
      - LINKSAVER_DB_USER=root
      - LINKSAVER_DB_PASS=root123
      - LINKSAVER_ISSUER_URI=https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_BkGi0vsAP
      - LINKSAVER_JWK_SET_URI=https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_BkGi0vsAP/.well-known/jwks.json
      - secret.API_KEY=api_key
    ports:
      - "8080:8080"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  db_data:
