spring:
  data:
    mongodb:
      authentication-database: ${LINKSAVER_AUTH_DB_NAME}
      host: ${LINKSAVER_DB_HOST}
      port: ${LINKSAVER_DB_PORT}
      database: ${LINKSAVER_DB_NAME}
      username: ${LINKSAVER_DB_USER}
      password: ${docker-secret-db-password}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LINKSAVER_ISSUER_URI}
          jwk-set-uri: ${LINKSAVER_JWK_SET_URI}

aws:
  region: ${AWS_REGION}
  cognito:
    client-id: ${COGNITO_CLIENT_ID}
    test-user-email: ${docker-secret-test-user-email}
    test-user-temporary-password: ${docker-secret-test-user-password}

secret:
  lambda:
    api-key: ${docker-secret-api-key}

docker-secret:
  bind-path: /run/secrets