server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: linksaver

mongock:
  enabled: true
  migration-repository-name: mongock-migrations
  default-author: Taha Bozdemir
  migration-scan-package: com.proto.linksaver.migration

