spring:
 data:
  mongodb:
    authentication-database: <MONGO_AUTH_DB_VAR>
    host: <MONGO_HOST_NAME>
    port:  <MONGO_HOST_PORT>
    database: <MONGO_DB_NAME>
    username: <MONGO_DB_USERNAME>
    password: <MONGO_DB_PASSWORD>

 security:
  oauth2:
   resourceserver:
    jwt:
      issuer-uri: <JWT_ISSUER_URI>
      jwk-set-uri: <JWK_SET_URI>

mongock:
  enabled: true
  migration-repository-name: mongock-migrations
  default-author: Taha Bozdemir
  migration-scan-package: com.proto.linksaver.migrations


aws:
  region: <AWS_REGION>
  cognito:
    clientId: <USER_POOL_APP_CLIENT_ID>
    testUserEmail: <USER_EMAIL>
    testUserTemporaryPassword: <USER_TEMP_PASSWORD>

secret:
  API_KEY: api-key

